
networks:
  default:

services:

  financedb:
    build: 
      dockerfile: mariadb.Dockerfile
    restart: always
    volumes:
      - ./migrations/mysql-migrations.sql.template:/docker-entrypoint-initdb.d/mysql-migrations.sql.template
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_APPLICATION_USER}
      MYSQL_PASSWORD: ${DB_APPLICATION_PASSWORD}
    networks:
      - default
    healthcheck:
      test: "mariadb --user=root --password=${DB_ROOT_PASSWORD} --execute \"SHOW DATABASES;\""
      timeout: 2s
      retries: 10
    command: > 
      sh -c "envsubst < /docker-entrypoint-initdb.d/mysql-migrations.sql.template > /docker-entrypoint-initdb.d/mysql-migrations.sql && exec docker-entrypoint.sh mariadbd"
  financeapp:
    image: tvergilio/finance:1.3
    environment:
      spring.datasource.url: jdbc:mariadb://financedb:3306/${DB_NAME}
      spring.datasource.username: ${DB_APPLICATION_USER}
      spring.datasource.password: ${DB_APPLICATION_PASSWORD}
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      financedb:
        condition: service_healthy
    networks:
      - default